version: '3'

services:
 
  jupyterlab:
     image: jupyter/base-notebook:latest
     container_name: jupyter
     ports:
       - 8888:8888
     volumes:
       - "./notebooks:/home/jovyan/work"
       - "./data:/home/jovyan/work/data"
     environment:
       - JUPYTER_ENABLE_LAB="yes"
     command: 
       sh -c 'pip install psycopg2-binary && start-notebook.sh'

  postgres:
     image: postgres
     container_name: postgres
     restart: always
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: movies
     volumes:
       - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./data:/var/lib/postgresql
