version: '3'

services:
 
  jupyterlab:
     image: jupyter/base-notebook:latest
     container_name: jupyter
     ports:
       - 8888:8888
     volumes:
       - "./notebooks:/home/jovyan/work"
     environment:
       - JUPYTER_ENABLE_LAB="yes"
     command: 
       sh -c 'pip install psycopg2-binary && start-notebook.sh'

  postgres:
     image: postgres
     container_name: postgres
     restart: always
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: movies

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
